name: Check code quality
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  quality:
    name: Ensure code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammatur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Setup cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching deps
        uses: actions/cache@v5
        with:
          path: $ {{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-latest-

      - name: Update composer
        run: composer self-update

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress  --optimize-autoloader

      - name: Check quality
        run: composer app:ensure-quality
